server.port=8080

# CORS
spring.web.cors.allowed-origins=http://localhost:5173,http://46.101.251.48:5173,http://46.101.251.48
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE
spring.web.cors.allowed-headers=*

# JSON
spring.jackson.serialization.indent-output=true
